'use client';

import { Suspense, useState, useEffect, useMemo } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import { MainHeader } from '@/components/main-header';
import { DashboardSites } from '@/components/dashboard-sites';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Loader2, ArrowLeft, Wand2, Play, CheckCircle2 } from 'lucide-react';
import { ContentGrid, GridColumn, GridRow } from '@/components/grid/content-grid';
import { MOCK_SITES, MOCK_COLLECTIONS, MOCK_ITEMS_BLOG, MOCK_SCHEMA_BLOG } from '@/lib/mock-data';
import { Collection, Site } from '@/lib/types';

// Dev Mode Dashboard
export default function DashboardPage() {
    const searchParams = useSearchParams();
    const router = useRouter();
    const isDevMode = searchParams.get('mode') === 'dev';
    
    // State for Dev Mode
    const [selectedCollectionId, setSelectedCollectionId] = useState<string | null>(null);
    const [gridData, setGridData] = useState<GridRow[]>([]);
    const [initialGridData, setInitialGridData] = useState<GridRow[]>([]);
    const [isGenerating, setIsGenerating] = useState(false);
    const [selectedRows, setSelectedRows] = useState<string[]>([]);

    useEffect(() => {
        if (isDevMode && selectedCollectionId) {
            // Load mock data for the selected collection
            // In a real app, this would fetch schema and items
            if (selectedCollectionId === 'mock-col-1') {
                const rows = MOCK_ITEMS_BLOG.map(item => ({
                    id: item.id,
                    data: item.fieldData,
                    status: 'idle'
                })) as GridRow[];
                setGridData(rows);
                setInitialGridData(rows);
            }
        }
    }, [isDevMode, selectedCollectionId]);

    // Detect how many fields differ from the initial snapshot so Publish can enable on edits
    const changedFieldCount = useMemo(() => {
        if (!initialGridData.length || !gridData.length) return 0;
        const initialById = initialGridData.reduce<Record<string, GridRow>>((acc, row) => {
            acc[row.id] = row;
            return acc;
        }, {});
        let total = 0;
        gridData.forEach(row => {
            const original = initialById[row.id];
            if (!original) return;
            const keys = new Set([...Object.keys(row.data), ...Object.keys(original.data)]);
            keys.forEach(key => {
                if (row.data[key] !== original.data[key]) {
                    total += 1;
                }
            });
        });
        return total;
    }, [gridData, initialGridData]);

    // Centralize publish state and log for easier debugging in dev mode
    const publishDisabled = useMemo(() => {
        return !selectedCollectionId || (selectedRows.length === 0 && changedFieldCount === 0) || isGenerating;
    }, [selectedCollectionId, selectedRows.length, changedFieldCount, isGenerating]);

    useEffect(() => {
        console.log('[dev-dashboard] publish state', {
            selectedCount: selectedRows.length,
            changedFieldCount,
            publishDisabled,
        });
    }, [selectedRows.length, changedFieldCount, publishDisabled]);

    const handleGenerateMock = () => {
        setIsGenerating(true);
        // Simulate generation
        setTimeout(() => {
            setGridData(current => current.map(row => {
                if (selectedRows.includes(row.id)) {
                    return {
                        ...row,
                        status: 'success',
                        data: {
                            ...row.data,
                            'post-summary': row.data['post-summary'] || 'Generated summary: This is a compelling summary of the article generated by AI.',
                            'post-body': row.data['post-body'] || '<p>Generated content: Here is the full body of the article exploring the depths of the topic with expert insights.</p>'
                        }
                    };
                }
                return row;
            }));
            setIsGenerating(false);
        }, 2000);
    };

    if (isDevMode) {
        // --- DEV MODE LAYOUT ---
        const activeCollection = MOCK_COLLECTIONS.find(c => c.id === selectedCollectionId);

        return (
            <div className="min-h-screen bg-background flex flex-col">
                {/* MainHeader should be provided by layout if this was a page, 
                    but as a client component replacing content, we might need it or rely on parent.
                    If this component replaces the WHOLE page including layout, we need it.
                    However, app/dashboard/page.tsx renders this component.
                    The layout app/dashboard/layout.tsx renders MainHeader.
                    So we should NOT render MainHeader here again. 
                */}
                
                <div className="border-b bg-muted/40 px-6 py-3 flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
                    <div className="flex items-center gap-4 flex-wrap">
                        <div className="flex items-center gap-2">
                            <span className="text-sm font-medium text-muted-foreground">Collections:</span>
                            <Select 
                                value={selectedCollectionId || ''} 
                                onValueChange={setSelectedCollectionId}
                            >
                                <SelectTrigger className="w-[200px] h-8">
                                    <SelectValue>{selectedCollectionId ? activeCollection?.display_name : "Select Collection"}</SelectValue>
                                </SelectTrigger>
                                <SelectContent>
                                    {MOCK_COLLECTIONS.map(col => (
                                        <SelectItem key={col.id} value={col.id}>
                                            {col.display_name}
                                        </SelectItem>
                                    ))}
                                </SelectContent>
                            </Select>
                        </div>
                        {activeCollection && (
                            <span className="text-xs text-muted-foreground border-l pl-4">
                                {activeCollection.site?.name}
                            </span>
                        )}
                    </div>

                    <div className="flex items-center gap-2 flex-wrap">
                        <Button 
                            size="sm" 
                            variant="default"
                            disabled={!selectedCollectionId || selectedRows.length === 0 || isGenerating}
                            onClick={handleGenerateMock}
                        >
                            {isGenerating ? (
                                <Loader2 className="w-4 h-4 animate-spin mr-2" />
                            ) : (
                                <Wand2 className="w-4 h-4 mr-2" />
                            )}
                            Generate Selected ({selectedRows.length})
                        </Button>
                        <Button 
                            size="sm" 
                            variant="outline" 
                            disabled={publishDisabled}
                        >
                            Publish
                        </Button>
                    </div>
                </div>

                <main className="flex-1 p-6 overflow-auto">
                    {!selectedCollectionId ? (
                        <div className="h-full flex flex-col items-center justify-center text-muted-foreground space-y-4">
                            <div className="p-4 bg-muted rounded-full">
                                <Play className="w-8 h-8 opacity-50" />
                            </div>
                            <p>Select a collection to start generating content.</p>
                        </div>
                    ) : (
                        <div className="space-y-4">
                            <ContentGrid 
                                columns={MOCK_SCHEMA_BLOG.map(col => ({
                                    id: col.name,
                                    label: col.displayName,
                                    type: col.type as any
                                }))} 
                                data={gridData}
                                onSelectionChange={setSelectedRows}
                                onCellEdit={(rowId, colId, val) => {
                                    // Update staged data locally so we can detect changes for Publish enabling
                                    setGridData(curr => curr.map(row => 
                                        row.id === rowId 
                                            ? { ...row, data: { ...row.data, [colId]: val } }
                                            : row
                                    ));
                                }}
                            />
                        </div>
                    )}
                </main>
            </div>
        );
    }

    // --- PRODUCTION LAYOUT (Original) ---
    // This part would normally render the real DashboardSites component
    // For now, we redirect to Connect if no integration (handled in Server Component normally)
    // But since this is a client component replacing the page, we need to handle auth check or let the server component do it.
    // Ideally, we keep the server component as the entry point.
    // Let's revert this file to the Server Component wrapper and make the dashboard content a client component.
    
    return null; // Should not happen if wrapped correctly
}

